# VexaShield - detects nginx rate-limit / connection-limit hits
[Definition]

failregex = limiting requests, excess .* client: <HOST>
            limiting connections, excess .* client: <HOST>

ignoreregex =
datepattern = %%Y/%%m/%%d %%H:%%M:%%S
