# VexaShield - kernel log: illegal TCP flag combinations (NULL/XMAS/SYN+FIN)
[Definition]

failregex = ^VS-SCAN: .*SRC=<HOST>
            ^VS-SCAN: .*SRC=<HOST>\s

ignoreregex =
datepattern = {^LN-BEG}

[Init]
journalmatch = _TRANSPORT=kernel
